Escolha = str(input('VocÃª quer converter para Celsius ou Farenheit? '))
if Escolha == ('Celsius'):
    valor = input('Valor: ')
    if float(valor) >= 0:
        print(float(valor) * 1.8 + 32)

if Escolha == ('Farenheit'):
    valor = input('Valor: ')
    if float(valor) >= 0:
        print((float(valor) - 32) / 1.8)






