Choose = str(input('VocÃª quer converter para Celsius ou Farenheit? '))
if Choose == ('Celsius'):
    Value = input('Value: ')
    if float(Value) >= 0:
        print(float(Value) * 1.8 + 32)

if Choose == ('Farenheit'):
    Value2 = input('Valor: ')
    if float(Value2) >= 0:
        print((float(Value2) - 32) / 1.8)






